### ISSUE TITLE
Refactor dot-even

### ISSUE THREAD

**Issue by arhimede** [dotkernel/dot-event#19]

**Comment by pinclau** [comment]
@alexmerlin  
The current implementation of dot-event just extends a class from laminas-event-manager and didnt do much, and if you want to create some events you need go throug all laminas-event-manager implementation every time to create an event (see dot-mail event implementation) [dot-mail](https://github.com/dotkernel/dot-mail/tree/4.0/src/Event)
We want to create a fully wrapper around event-manager, so we can make use of dot-event to create events in a much easier way, like dot-controller events, when you register the events/listenters in the ConfgProvider and you can trigger them whenever you want. 
So in this implementation, we whould register all the events under the dot-event config, and we could trigger them wherever we want (directly in a repository, or in a service for example)
